# Generated by Django 4.2.11 on 2026-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
